# Generated by Django 4.2.23 on 2026-07-26 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('nomeUtente', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('eMail', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Utente',
            },
        ),
        migrations.CreateModel(
            name='RispostaUtenteQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codicePartecipazione', models.IntegerField()),
                ('numeroRisposta', models.IntegerField()),
                ('numeroDomanda', models.IntegerField()),
                ('codiceQuiz', models.IntegerField()),
            ],
            options={
                'db_table': 'RispostaUtenteQuiz',
                'unique_together': {('codicePartecipazione', 'numeroRisposta', 'numeroDomanda', 'codiceQuiz')},
            },
        ),
        migrations.CreateModel(
            name='Risposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('numeroDomanda', models.IntegerField()),
                ('codiceQuiz', models.IntegerField()),
                ('testo', models.TextField()),
                ('tipo', models.CharField(choices=[('Corretta', 'Corretta'), ('Sbagliata', 'Sbagliata')], default='Sbagliata', max_length=10)),
                ('punteggio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'Risposta',
                'unique_together': {('numero', 'numeroDomanda', 'codiceQuiz')},
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('codice', models.AutoField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=200)),
                ('dataInizio', models.DateField()),
                ('dataFine', models.DateField()),
                ('creatore', models.ForeignKey(db_column='creatore', on_delete=django.db.models.deletion.RESTRICT, to='quiz.utente')),
            ],
            options={
                'db_table': 'Quiz',
            },
        ),
        migrations.CreateModel(
            name='Partecipazione',
            fields=[
                ('codice', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('codiceQuiz', models.ForeignKey(db_column='codiceQuiz', on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('nomeUtente', models.ForeignKey(db_column='nomeUtente', on_delete=django.db.models.deletion.RESTRICT, to='quiz.utente')),
            ],
            options={
                'db_table': 'Partecipazione',
            },
        ),
        migrations.CreateModel(
            name='Domanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('testo', models.TextField()),
                ('codiceQuiz', models.ForeignKey(db_column='codiceQuiz', on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
            options={
                'db_table': 'Domanda',
                'unique_together': {('numero', 'codiceQuiz')},
            },
        ),
    ]
